name: android-build

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: ${{ hashFiles('app/android/gradlew') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x app/android/gradlew
      - name: Build
        working-directory: app/android
        run: ./gradlew build
      - name: Assemble Debug
        working-directory: app/android
        run: ./gradlew assembleDebug
