name: server-build

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: ${{ hashFiles('server/**') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Build server
        working-directory: server
        run: |
          go mod init example.com/bonding || true
          go build ./...
      - name: Docker build
        if: ${{ hashFiles('server/Dockerfile') != '' }}
        working-directory: server
        run: docker build -t bonding-server:ci .
